module.exports = {
  _: {
    storage_is_encrypted: 'Shramba je šifrirana. Za dešifriranje je potrebno geslo',
    enter_password: 'Vnesite geslo',
    bad_password: 'Napačno geslo, prosimo poskusite ponovno.',
    never: 'nikoli',
    continue: 'Nadaljuj',
    ok: 'OK',
  },
  wallets: {
    select_wallet: 'Izberite Denarnico',
    options: 'možnosti',
    createBitcoinWallet:
      'Trenutno nimate ustvarjene Bitcoin denarnice. Za uporabo Lightning denarnice je potrebno ustvariti ali uvoziti Bitcoin denarnico. Ali želite kljub temu nadaljevati?',
    list: {
      app_name: 'BlueWallet',
      title: 'denarnice',
      header: 'Denarnica predstavlja par, skrivnost (zasebni ključ) in naslov,' + 'ki ga lahko delite za prejemanje kovancev.',
      add: 'Dodajte denarnico',
      create_a_wallet: 'Ustvarite denarnico',
      create_a_wallet1: "Je brezplačno in lahko jih ustvarite",
      create_a_wallet2: 'toliko, kot želite',
      create_a_button: 'Ustvarite',
      latest_transaction: 'zadnja transakcija',
      empty_txs1: 'Tu bodo prikazane vaše transakcije',
      empty_txs2: 'Začnite uporabljati denarnico',
      empty_txs1_lightning:
        'Lightning denarnica je namenjena za vsakodnevne transakcije. Provizije so nepošteno poceni in hitrost je izjemno hitra.',
      empty_txs2_lightning: '\nČe želite začeti z uporabo, tapnite na "upravljanje sredstev" in napolnite denarnico.',
      tap_here_to_buy: 'Kupite Bitcoin',
    },
    reorder: {
      title: 'Preureditev Denarnic',
    },
    add: {
      title: 'ustvarite denarnico',
      description:
        'Skenirate lahko varnostno kopijo papirnate denarnice (v WIF - Wallet Import Format), ali ustvarite novo denarnico. Segwit denarnice so privzeto podprte.',
      scan: 'Skeniraj',
      create: 'Ustvari',
      label_new_segwit: 'Nova SegWit',
      label_new_lightning: 'Nova Lightning',
      wallet_name: 'ime',
      wallet_type: 'tip',
      or: 'ali',
      import_wallet: 'Uvozi denarnico',
      imported: 'Uvoženo',
      coming_soon: 'Prihaja kmalu',
      lightning: 'Lightning',
      bitcoin: 'Bitcoin',
    },
    details: {
      title: 'Denarnica',
      address: 'Naslov',
      master_fingerprint: 'Master fingerprint',
      type: 'Tip',
      label: 'Oznaka',
      destination: 'cilj',
      description: 'opis',
      are_you_sure: 'Ali ste prepričani?',
      yes_delete: 'Da, izbriši',
      no_cancel: 'Ne, prekliči',
      delete: 'Izbriši',
      save: 'Shrani',
      delete_this_wallet: 'Izbriši to denarnico',
      export_backup: 'Izvozi / varnostna kopija',
      buy_bitcoin: 'Kupite Bitcoin',
      show_xpub: 'Prikaži XPUB denarnice',
      connected_to: 'Povezano z',
      advanced: 'Napredno',
      use_with_hardware_wallet: 'Uporaba s strojno denarnico',
    },
    export: {
      title: 'izvoz denarnice',
    },
    xpub: {
      title: 'XPUB denarnice',
      copiedToClipboard: 'Kopirano v odložišče.',
    },
    import: {
      title: 'uvoz',
      explanation:
        "Tu napišite vaš seznam besed, zasebni ključ, WIF, ali karkoli drugega imate. BlueWallet se bo potrudil uganiti pravilno obliko in uvoziti vašo denarnico",
      imported: 'Uvoženo',
      error: 'Napaka pri uvozu. Prosimo, preverite ali so podani podatki pravilni.',
      success: 'Uspešno',
      do_import: 'Uvozi',
      scan_qr: 'Skenirajte ali uvozite datoteko',
    },
    scanQrWif: {
      go_back: 'Nazaj',
      cancel: 'Prekliči',
      decoding: 'Dekodiranje',
      input_password: 'Vnesite geslo',
      password_explain: 'To je BIP38 šifriran zasebni ključ',
      bad_password: 'Napačno geslo',
      wallet_already_exists: 'Ta denarnica že obstaja',
      bad_wif: 'Neveljaven WIF',
      imported_wif: 'Uvožen WIF ',
      with_address: ' z naslovom ',
      imported_segwit: 'Uvožen SegWit',
      imported_legacy: 'Uvožen Legacy',
      imported_watchonly: 'Uvožen Watch-only',
    },
  },
  transactions: {
    list: {
      tabBarLabel: 'Transakcije',
      title: 'transakcije',
      description: 'Seznam vhodnih ali odhodnih transakcij vaših denarnic',
      conf: 'potrd',
    },
    details: {
      title: 'Transakcija',
      from: 'Vhod',
      to: 'Izhod',
      copy: 'Kopiraj',
      transaction_details: 'Podrobnosti transakcije',
      show_in_block_explorer: 'Prikaži v raziskovalcu blokov',
    },
  },
  send: {
    header: 'Pošlji',
    details: {
      title: 'ustvari transakcijo',
      amount_field_is_not_valid: 'Znesek ni veljaven',
      fee_field_is_not_valid: 'Omrežnina ni veljavna',
      address_field_is_not_valid: 'Naslov ni veljaven',
      total_exceeds_balance: 'Znesek presega razpoložljivo stanje.',
      create_tx_error: 'Prišlo je do napake pri ustvarjanju transakcije. Prosimo, preverite ali je naslov veljaven.',
      address: 'naslov',
      amount_placeholder: 'znesek (v BTC)',
      fee_placeholder: 'in omrežnina (v BTC)',
      note_placeholder: 'lastna opomba',
      cancel: 'Prekliči',
      scan: 'Skeniraj',
      send: 'Pošlji',
      create: 'Ustvari Račun',
      remaining_balance: 'Preostalo stanje',
    },
    confirm: {
      header: 'Potrditev',
      sendNow: 'Pošlji',
    },
    success: {
      done: 'Končano',
    },
    create: {
      details: 'Podrobnosti',
      title: 'ustvari transakcijo',
      error: 'Napaka pri ustvarjanju transakcije. Neveljaven naslov ali znesek?',
      go_back: 'Nazaj',
      this_is_hex: `To je šestnajstiška vrednost transakcije, podpisana in pripravljena za objavo v omrežju.`,
      to: 'Za',
      amount: 'Znesek',
      fee: 'Omrežnina',
      tx_size: 'Velikost transakcije',
      satoshi_per_byte: 'Satoshi na bajt',
      memo: 'Opomba',
      broadcast: 'Objavi v omrežju',
      not_enough_fee: 'Prenizka omrežnina. Zvišajte omrežnino',
    },
  },
  receive: {
    header: 'Prejmi',
    details: {
      title: 'Ta naslov delite s plačnikom',
      share: 'deli',
      copiedToClipboard: 'Kopirano v odložišče.',
      label: 'Opis',
      create: 'Ustvari',
      setAmount: 'Prejmi znesek',
    },
    scan_lnurl: 'Skenirajte za prejemanje',
  },
  buyBitcoin: {
    header: 'Kupite Bitcoin',
    tap_your_address: 'Za kopiranje v odložišče tapnite vaš naslov:',
    copied: 'Kopirano v odložišče!',
  },
  settings: {
    header: 'nastavitve',
    plausible_deniability: 'Verodostojno zanikanje',
    storage_not_encrypted: 'Shramba: ni šifrirano',
    storage_encrypted: 'Shramba: šifrirano',
    password: 'Geslo',
    password_explain: 'Ustvarite geslo za dešifriranje shrambe',
    retype_password: 'Ponovno vpišite geslo',
    passwords_do_not_match: 'Gesli se ne ujemata',
    encrypt_storage: 'Šifriraj shrambo',
    lightning_settings: 'Lightning Nastavitve',
    lightning_settings_explain:
      'Za povezavo z lastnim LND vozliščem, prosimo namestite LndHub' +
      " in vnesite URL vozlišča v nastavitve. Pustite prazno za uporabo BlueWallet LNDHub (lndhub.io). Denarnice ustvarjene po potrditvi sprememb bodo povezane z novim LNDHub-om.",
    electrum_settings: 'Electrum Nastavitve',
    electrum_settings_explain: 'Pustite prazno za uporabo privzetih nastavitev',
    save: 'Shrani',
    about: 'O aplikaciji',
    language: 'Jezik',
    currency: 'Valuta',
    advanced_options: 'Napredne Možnosti',
    enable_advanced_mode: 'Napredni način',
  },
  plausibledeniability: {
    title: 'Verodostojno Zanikanje',
    help:
      'V določenih okoliščinah boste morda prisiljeni razkriti ' +
      'geslo. Da zavarujete vaša sredstva, lahko BlueWallet ustvari dodatno ' +
      'šifrirano shrambo z drugačnim geslom. Pod prisilo, ' +
      'lahko to geslo razkrijete tretji osebi. Če ga vnesete v ' +
      "BlueWallet, bo odklenilo 'lažno' shrambo. To se bo tretji " +
      'osebi zdelo verodostojno, vaša skrivna glavna shramba s pravimi sredstvi pa ' +
      'bo ostala varna.',
    help2: 'Nova shramba bo popolnoma funkcionalna, za večjo verodostojnost ' + 'lahko tam hranite manjši znesek.',
    create_fake_storage: 'Ustvari Šifrirano shrambo',
    go_back: 'Nazaj',
    create_password: 'Ustvarite geslo',
    create_password_explanation: 'Geslo za lažno shrambo se ne sme ujemati z geslom glavne shrambe',
    password_should_not_match: 'Geslo je trenutno v uporabi. Prosimo, poskusite z drugim geslom.',
    retype_password: 'Ponovno vpišite geslo',
    passwords_do_not_match: 'Gesli se ne ujemata, poskusite ponovno',
    success: 'Uspešno',
  },
  lnd: {
    title: 'upravljanje sredstev',
    choose_source_wallet: 'Izberite izvorno denarnico',
    refill_lnd_balance: 'Napolni stanje Lightning denarnice',
    refill: 'Napolni',
    withdraw: 'Dvig',
    expired: 'Potekel',
    placeholder: 'Račun',
    sameWalletAsInvoiceError: 'Plačilo računa ni mogoče z denarnico, s katero je bil ustvarjen.',
  },
  pleasebackup: {
    title: 'Vaša denarnica je ustvarjena...',
    text:
      "Prosimo zapišite si seznam besed (mnemonično seme) na list papirja. To je varnostna kopija, ki jo lahko uporabite za obnovitev denarnice na drugi napravi.",
    ok: 'V redu, sem si zapisal!',
  },
  lndViewInvoice: {
    wasnt_paid_and_expired: 'Ta račun ni bil plačan in je potekel',
    has_been_paid: 'Ta račun je bil plačan',
    please_pay: 'Prosim plačajte',
    sats: 'sats',
    for: 'Za:',
    additional_info: 'Dodatne Informacije',
    open_direct_channel: 'Odpri neposreden kanal s tem vozliščem:',
  },
};
